### ISSUE TITLE
Modifica uml cancellaCliente

### ISSUE THREAD

**Issue by alepast85** [luca-lezzerini/sigeba2#21]
Il metodo del controller anagraficaClienteController dovrebbe accettare CriterioCancellazioneClienteDto.
![image](https://user-images.githubusercontent.com/109357231/182157449-b58c3580-4ef3-4513-a7f2-f48b25e72e10.png)

**Comment by luca-lezzerini** [comment]
Risolto al commit e00368ba8bedb90212b95f4f6af4e08fbe02872d
